# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ex2-5-8' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Messaging'
  # Pods for ex2-5-8

  target 'ex2-5-8Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ex2-5-8UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
