# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ex2-4-3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 2.0'
pod 'FMDB'
  # Pods for ex2-4-3

  target 'ex2-4-3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ex2-4-3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
